/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pharmacyproject;

import java.sql.DriverManager;
import java.sql.SQLException;
import net.proteanit.sql.DbUtils;
import java.sql.Statement;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Date;
import java.text.SimpleDateFormat;
import Project.ConnectionProvider;
/**
 *
 * @author Admin
 */
public class Selling extends javax.swing.JFrame {

    /**
     * Creates new form Selling
     */
    public Selling() {
        initComponents();
        SelectMed();
        showDate();
    }

    public void showDate(){
        Date d=new Date();
        SimpleDateFormat s=new SimpleDateFormat("dd-MM-yyyy");
        DateLabel.setText(s.format(d));
    }
    Connection con=null;
    Statement st=null;
    ResultSet rs=null;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        BillId = new javax.swing.JTextField();
        MedName = new javax.swing.JTextField();
        Addbutton1 = new javax.swing.JButton();
        UpdateButton1 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        Clear1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        MedTable = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        DateLabel = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        MedQty = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        BillText = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(204, 255, 0));

        jLabel24.setFont(new java.awt.Font("Algerian", 1, 30)); // NOI18N
        jLabel24.setText("PHARMACY MANAGEMENT SYSTEM");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Medicine");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Agents");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("Company");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel15.setText("Billing");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("Bill ID");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("Medicine");

        Addbutton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Addbutton1.setLabel("Add To Bill");
        Addbutton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Addbutton1MouseClicked(evt);
            }
        });
        Addbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Addbutton1ActionPerformed(evt);
            }
        });

        UpdateButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UpdateButton1.setText("Print");
        UpdateButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateButton1MouseClicked(evt);
            }
        });
        UpdateButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButton1ActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel22.setText("Bill");

        Clear1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Clear1.setText("Clear");
        Clear1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Clear1MouseClicked(evt);
            }
        });

        MedTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "MedName", "Med Price", "Med Quantity", "Med Feb Date", "Med Exp Date", "Company"
            }
        ));
        MedTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MedTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(MedTable);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setText("Seller");

        DateLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DateLabel.setText("Date");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel21.setText("Medicine Table");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setText("QTY");

        BillText.setColumns(20);
        BillText.setRows(5);
        BillText.setText("\t*********************************** Pharma Center ********************************************");
        jScrollPane3.setViewportView(BillText);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel18)
                .addGap(308, 308, 308)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DateLabel)
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(UpdateButton1)
                .addGap(405, 405, 405))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel23))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MedQty, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BillId, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MedName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel21)
                                .addGap(229, 229, 229))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel22)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(Addbutton1)
                                    .addGap(37, 37, 37)
                                    .addComponent(Clear1)
                                    .addGap(112, 112, 112))))))
                .addContainerGap(10, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(46, 46, 46)
                    .addComponent(jLabel19)
                    .addContainerGap(606, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(DateLabel))
                        .addGap(83, 83, 83)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(MedName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BillId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16))
                                .addGap(65, 65, 65)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel23)
                                    .addComponent(MedQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Addbutton1)
                    .addComponent(Clear1))
                .addGap(18, 18, 18)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                .addGap(24, 24, 24)
                .addComponent(UpdateButton1)
                .addContainerGap())
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(91, 91, 91)
                    .addComponent(jLabel19)
                    .addContainerGap(299, Short.MAX_VALUE)))
        );

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacyproject/Close.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Algerian", 1, 30)); // NOI18N
        jLabel20.setText("PHARMACY MANAGEMENT SYSTEM");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18))
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel20)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel20)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void SelectMed(){
        try{
            con=ConnectionProvider.getCon();
//            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmadb","root","rajat");
            st=con.createStatement();
            rs=st.executeQuery("select * from medicinetable");
            MedTable.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(SQLException e){
            e.printStackTrace();
        }
    }
    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        //Medicine
        new Medicine().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        //Agent
        new Agents().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel11MouseClicked
    int i=0,price,MedId,OldQty;
    public void update(){
        int newQty;
        newQty = OldQty - Integer.valueOf(MedQty.getText());
        try{
            con=ConnectionProvider.getCon();
//            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmadb","root","rajat");
            String query="update medicinetable set MedQty='"+newQty+"'"+" where MedId= "+MedId;
            st=con.createStatement();
            st.executeUpdate(query);
           JOptionPane.showMessageDialog(this,"Updated successfully");
        }catch(Exception e){
            e.printStackTrace();
        }
        SelectMed();
    }
    
    private void Addbutton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Addbutton1MouseClicked
        // TODO add your handling code here:
        // for Add Button
        if(MedName.getText().isEmpty() || MedQty.getText().isEmpty() || BillId.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Enter All Information.");
        }else{
            int Qty=Integer.parseInt(MedQty.getText());
            if(OldQty<Qty){
                JOptionPane.showMessageDialog(null,"Stock Not Avilable");
            }else{
                i++;
                update();
                if(i==1){
                BillText.setText(BillText.getText()+"\n"
                + "\t ID \t Medicine \t QTY \t Price \t Total \n\t"+
                ""+i+" \t "+MedName.getText()+" \t "+MedQty.getText()+" \t "+price+" \t "+Integer.valueOf(MedQty.getText())*price);
                }else{
                    BillText.setText(BillText.getText() +"\n\t"+i+"\t" +MedName.getText()+" \t "+MedQty.getText()+" \t "+price+" \t "+Integer.valueOf(MedQty.getText())*price);
                }
            }
        }
//        if(CId.getText().isEmpty() || CName.getText().isEmpty() || CAddress.getText().isEmpty() || CExp.getText().isEmpty() || CPhone.getText().isEmpty()){
//            JOptionPane.showMessageDialog(this,"Information Messing");
//        }else{
//            boolean isUnique=true;
//            try{
//                con=DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmadb","root","rajat");
//                Statement st1=con.createStatement();
//                ResultSet rs1=st1.executeQuery("Select * from companytable where CId="+CId.getText());
//                if(rs1.next()){
//                    isUnique=false;
//                    JOptionPane.showMessageDialog(this,"Please Enter Uniqe Id");
//                }
//            }catch(Exception e){
//                e.printStackTrace();
//            }
//            if(isUnique==true){
//                try{
//                    con=DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmadb","root","rajat");
//                    //            con=ConnectionProvider.getCon();
//                    PreparedStatement add=con.prepareStatement("insert into companytable values(?,?,?,?,?)");
//                    add.setInt(1,Integer.valueOf(CId.getText()));
//                    add.setString(2,CName.getText());
//                    add.setString(3, CAddress.getText());
//                    add.setString(4,CExp.getText());
//                    add.setString(5,CPhone.getText());
//                    int row=add.executeUpdate();
//                    JOptionPane.showMessageDialog(this,"Added SuccessFully");
//                    con.close();
//                    SelectMed();
//                }catch(SQLException e){
//                    e.printStackTrace();
//                }
//            }
//        }

    }//GEN-LAST:event_Addbutton1MouseClicked

    private void Addbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Addbutton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Addbutton1ActionPerformed

    private void UpdateButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateButton1MouseClicked
        // TODO add your handling code here:
        //For Print Button
//        if(rowSelected==false){
//            JOptionPane.showMessageDialog(this,"Row is Not Selected.");
//        }else if(CId.getText().isEmpty() || CName.getText().isEmpty() || CAddress.getText().isEmpty() || CExp.getText().isEmpty() || CPhone.getText().isEmpty()){
//            JOptionPane.showMessageDialog(this,"Information Messing");
//        }else{
//            try{
//                con=DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmadb","root","rajat");
//                String query="update companytable set CName='"+CName.getText()+"'"+", CAddress ='"+CAddress.getText()+"'"+",CExp='"+CExp.getText()+"'"+",CPhone='"+CPhone.getText()+"'"+" where CId = "+CId.getText();
//                Statement add=con.createStatement();
//                add.executeUpdate(query);
//                JOptionPane.showMessageDialog(this,"Updated SuccessFully");
//
//            }catch(SQLException e){
//                e.printStackTrace();
//            }catch(Exception e){
//                JOptionPane.showMessageDialog(this,"Enter Dates Properly");
//            }
//            SelectMed();
//        }

        try{
            BillText.print();
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_UpdateButton1MouseClicked

    private void Clear1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Clear1MouseClicked
        // TODO add your handling code here:
        //Clear Button
        BillId.setText("");
        MedName.setText("");
        MedQty.setText("");
//        CExp.setText("");
//        CPhone.setText("");
    }//GEN-LAST:event_Clear1MouseClicked

    private void MedTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MedTableMouseClicked
        // TODO add your handling code here:
        //For Table Row Selecting
        DefaultTableModel model= (DefaultTableModel)MedTable.getModel();
        int Myindex=MedTable.getSelectedRow();
        MedName.setText(model.getValueAt(Myindex, 1).toString());
        price=Integer.valueOf(model.getValueAt(Myindex,2).toString());
        MedId=Integer.valueOf(model.getValueAt(Myindex,0).toString());
        OldQty = Integer.valueOf((model.getValueAt(Myindex,3).toString()));
//        MedName.setText(model.getValueAt(Myindex, 1).toString());
//        MedPrice.setText(model.getValueAt(Myindex, 2).toString());
//        MedQty.setText(model.getValueAt(Myindex,3).toString());
//        rowSelected=true;
//        MedFeb.setDate(model.getValueAt(Myindex, 4).toString());
    }//GEN-LAST:event_MedTableMouseClicked

    private void UpdateButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        new Company().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel14MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Selling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Selling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Selling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Selling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Selling().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addbutton1;
    private javax.swing.JTextField BillId;
    private javax.swing.JTextArea BillText;
    private javax.swing.JButton Clear1;
    private javax.swing.JLabel DateLabel;
    private javax.swing.JTextField MedName;
    private javax.swing.JTextField MedQty;
    private javax.swing.JTable MedTable;
    private javax.swing.JButton UpdateButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
